BEBoP-WebUserInterfaces/src/main/java/ContentBean.java
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import org.icefaces.ace.component.fileentry.FileEntry;
import org.icefaces.ace.component.fileentry.FileEntryEvent;
import org.icefaces.ace.component.fileentry.FileEntryResults;

import eu.learnpad.verification.plugin.bpmn.guideline.factory.GuidelinesFactory;





@ManagedBean(name="ContentBean")
@RequestScoped
public class ContentBean implements Serializable{


	/**
	 * 
	 */
	private static final long serialVersionUID = 2574895928017048791L;

	private int id;
	private String Content;
	private String restid;
	private String filecontent;
	private String filename;
	private String status;
	private String Language;
	private GuidelinesFactory guidelinesfactory;
	private String example;



	public ContentBean(){
		
	}

	@PostConstruct
    public void initialize() {

    }

	public String getExample() {
		return example;
	}

	public void setExample(String example) {
		this.example = example;
	}

	public void changeLanguage(ValueChangeEvent e) {
		this.Language = e.toString();
	}
	
	public String getLanguage() {
		return this.Language ;
	}

	public void setLanguage(String l) {
		this.Language = l;
	}


	public GuidelinesFactory getGuidelinesfactory() {
		return guidelinesfactory;
	}






	public void setGuidelinesfactory(GuidelinesFactory guidelinefactory) {
		this.guidelinesfactory = guidelinefactory;
	}






	public String getFilename() {
		return filename;
	}

	public void setName(String name) {
		 filename = name;
	}











	public String getFilecontent() {
		return filecontent;
	}


	public void setFilecontent(String filecontent) {
		this.filecontent = filecontent;
	}


	public String getRestid() {
		return restid;
	}



	public void setRestid(String restid) {
		this.restid = restid;
	}




	public String getContent() {
		return Content;
	}



	public void setContent(String content) {
		Content = content;
	}

	public String getStatus() {
		return status;
	}



	public void setStatus(String status) {
		this.status = status;
	}

	public void sampleListener(FileEntryEvent e) {
		FileEntry fe = (FileEntry)e.getComponent();
		FileEntryResults results = fe.getResults();

		for (FileEntryResults.FileInfo fileInfo : results.getFiles()) {
			System.out.println(fileInfo);


			if (fileInfo.isSaved()) {
				// Process the file. Only save cloned copies of results or fileInfo,StandardCharsets.UTF_8

				Path path = Paths.get(fileInfo.getFile().getAbsolutePath());
				try {
					filecontent = 	new String(Files.readAllBytes(path), "UTF8");
					filename = fileInfo.getFile().toString();// fileInfo.getFileName();
					System.out.println(filecontent);
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		}

	}

	
	
	
	public void GENExample(String name) {
		
		test(name);
	}
	


	public List<String> getAllResouce(){
		String sep = File.separator;
		List<String> resourcesDir = new ArrayList<String>();
		resourcesDir.add("EPBR"+sep);
		resourcesDir.add("test"+sep);
		resourcesDir.add("model"+sep);
		List<String> files = new ArrayList<String>();
		try {
		
			
			for(String resourceDir: resourcesDir){
			URL url = ContentBean.class.getResource(resourceDir);
			if (url == null) {
			     // error - missing folder
			} else {
			    File dir = new File(url.toURI());
			    for (File nextFile : dir.listFiles()) {
			        // Do something with nextFile
			    	files.add(resourceDir+nextFile.getName());
			    }
			}
			}
		
			return files;
		} catch ( URISyntaxException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		/*for(String f : files){
		  String data= IOUtils.toString(Thread.currentThread().getClass().getClassLoader().getResourceAsStream(resourceDir + f));
		  ....process data
		}*/
		
		return null;
	}

	private void test(String name) {
		try {
			
			URL is = ContentBean.class.getClassLoader().getResource(name);
			Path path = Paths.get(is.toURI());

			filecontent = 	new String(Files.readAllBytes(path), "UTF8");

			filename = path.toFile().toString();// fileInfo.getFileName();
			send();
		} catch (IOException | URISyntaxException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}






	public void submitButton(ActionEvent event) {
		send();
	}

	public void send(){
		if(filecontent!=null){

			Client client = ClientBuilder.newClient();
			String lang = "en";
			if(Language!=null){
				if( Language.equals("Italian")){
					lang = "it";
				}
			}
			WebTarget target = client.target("http://localhost:8080").path("BEBoP-1/validatemodel/put").queryParam("lang", lang);


			Entity<String> entity = Entity.entity(filecontent,MediaType.TEXT_PLAIN);

			Response response =  target.request(MediaType.TEXT_PLAIN).post(entity);

			String id = response.readEntity(String.class);

			FacesContext context = FacesContext.getCurrentInstance();
			context.getExternalContext().getRequestMap().put("rest", id);

			//context.getApplication().evaluateExpressionGet(context, "#{ContentAnalysisBean.setId("+id+")}", String.class);

			this.setRestid(id);

			System.out.println("Submit Clicked: " + Content + ", " + id + "; ");


			target = client.target("http://localhost:8080").path("BEBoP-1/validatemodel/"+id+"/status");
			String 	status ="";
			while (!status.equals("OK")) {


				status = target.request().get(String.class);

				this.setStatus(status);
			}
			System.out.println("Status: "+status);


			target = client.target("http://localhost:8080").path("BEBoP-1/validatemodel/"+id);
			Response response2 =  target.request().get();

			GuidelinesFactory glres = response2.readEntity(GuidelinesFactory.class);
			this.setGuidelinesfactory(glres);
			// context = FacesContext.getCurrentInstance();
			//context.getExternalContext().getRequestMap().put("guidelinefactory", glres);

			//GuidelinesFactory res = context.
			//getApplication().
			//evaluateExpressionGet(context, "#{ContentAnalysis.guidelinefactory}", GuidelinesFactory.class);



			//System.out.println("Guideline: "+this.getGuidelinesfactory());
			//this.setCollectionannotatedcontent(
			//annotatecontent.readEntity(
			//new GenericType<Collection<AnnotatedCollaborativeContentAnalysis>>() {}));



		}
	}
}

BEBoP-WebUserInterfaces/src/main/java/PageController.java
import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.ActionEvent;

@ManagedBean(name="pageController")
@SessionScoped
public class PageController implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 4584289279328839768L;

	public String navigatePage1() {
		System.out.println("Redirect to Page 1");
		
		return "page1?faces-redirect=true";
	}
	
	public String navigatePage2() {
		System.out.println("Redirect to Page 2");
		
		return "page2?faces-redirect=true";
	}
	
	public String navigatePageGetAnalysis() {
		System.out.println("Redirect to Page getanalysis");
		
		return "getanalysis?faces-redirect=true";
	}
	
	public String navigatepageAnalysis(){
		System.out.println("Redirect to Page Analysis");
		return "pageAnalysis?faces-redirect=true";
	}
	
	public String navigatePageCF() {
		System.out.println("Redirect to Page form");
		
		return "contentform?faces-redirect=true";
	}
	
	public String action() {
		System.out.println("Action Fired");
		
		return null;
	}
	
	public void actionListener(ActionEvent event) {
		System.out.println("ActionListener Fired");
	}
}

BEBoP-WebUserInterfaces/src/main/webapp/contentform.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:icecore="http://www.icefaces.org/icefaces/core"
	xmlns:ace="http://www.icefaces.org/icefaces/components"
	xmlns:ice="http://www.icesoft.com/icefaces/component"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
<f:metadata>
    <f:viewParam name="example" value="#{ContentBean.example}" />
</f:metadata>
<h:head>
	<title>Single Submit - Form</title>
</h:head>
<h:body>
<ace:submitMonitor blockUI="@all" idleLabel="Not currently submitting"
    activeLabel="Busy submitting to server..." for="Form" serverErrorLabel="Server error"
                                       networkErrorLabel="Network error"
                                       sessionExpiredLabel="Session expired" />
	<h:form>
		<h:panelGrid columns="3" border="0">
		<f:facet name="header">
		<h:outputText value="User Interface for BEBoP*"/>
		
		
		</f:facet>
		<h:outputLabel for="language" value="Language:" />
			<h:selectOneMenu id="language" value="#{ContentBean.language}"  required="true">
				<f:selectItem itemValue="English" />
				<f:selectItem itemValue="Italian" />
				
			</h:selectOneMenu>
			<h:message for="language" />
			
			<h:outputLabel for="inputfile" value="Input BPMN File:" />
			<ace:fileEntry id="inputfile"  required="true"
				fileEntryListener="#{ContentBean.sampleListener}" immediate="true"
				maxFileCount="1" maxFileSizeMessage="File size cannot exceed 1 MB" maxFileSize="1024000" />
			<h:message for="inputfile" />
			
			

			
			
		</h:panelGrid>


		<h:commandButton value="Submit"
			action="#{pageController.navigatePageGetAnalysis}"
			actionListener="#{ContentBean.submitButton}" >
   <f:setPropertyActionListener target="#{DataAnalysis.guidelinesfactory}"  value="#{ContentBean.guidelinesfactory}" />
   <f:setPropertyActionListener target="#{DataAnalysis.filename}"  value="#{ContentBean.filename}" />
    <f:setPropertyActionListener target="#{DataAnalysis.xmldata}"  value="#{ContentBean.filecontent}" />
</h:commandButton>

<h:commandButton value="Refresh" action="#{pageController.navigatePageCF}" immediate="true"/>

	</h:form>

	<br />
<h:form>
	<h:panelGrid columns="2" border="0">
		<f:facet name="header">
			Examples
		</f:facet>
		
<c:forEach items="#{ContentBean.allResouce}" var="item" varStatus="status">
	<h:outputLabel  value="#{item}" />
	
	<h:commandButton  value="Submit" action="#{pageController.navigatePageGetAnalysis}"
			actionListener="#{ContentBean.GENExample(item)}" > 
	
	<f:setPropertyActionListener target="#{DataAnalysis.guidelinesfactory}"  value="#{ContentBean.guidelinesfactory}" />
   <f:setPropertyActionListener target="#{DataAnalysis.filename}"  value="#{ContentBean.filename}" />
    <f:setPropertyActionListener target="#{DataAnalysis.xmldata}"  value="#{ContentBean.filecontent}" /></h:commandButton>
	

</c:forEach>


	</h:panelGrid>
	</h:form>
	<br/>

<p>*This work has been partially founded by <a href="http://www.learnpad.eu" target="_blank">EU project LearnPAd</a>  (GA:619583).</p>

<br/>
<br/>
<h:panelGrid columns="2" border="0" layout="block">
<h:panelGroup>
<div style="width: 600px;">
<p align="center">
 <a href="http://www.fmt.isti.cnr.it" target="_blank">Formal Methods &amp; Tools Group</a><br/>
<a href="http://www.isti.cnr.it" target="_blank">Institute of information science and technologies "Alessandro Faedo"</a><br/>  
<a href="http://www.cnr.it" target="_blank"><img  src="images/Logo_CNR-2010-ENG-high.png" style="height: 80px;" /></a>
</p>
</div>
</h:panelGroup>
<h:panelGroup>
<div style="width: 300px;">
<p align="center">
<a href="http://www.cs.unicam.it/" target="_blank">Computer Science Division</a><br/>
<a href="http://www.cs.unicam.it/" target="_blank">University of Camerino</a><br/>
<a href="http://www.unicam.it" target="_blank"><img  src="images/Logo_unicam.png" style="height: 80px; "  /></a><br/>
</p>
</div>
</h:panelGroup>
</h:panelGrid>
	<br/>

<p>*For any bugs, please write to Giorgio O. Spagnolo (spagnolo at isti.cnr.it)</p>


</h:body>
</html>

BEBoP-WebUserInterfaces/src/main/webapp/getanalysis.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:icecore="http://www.icefaces.org/icefaces/core"
	xmlns:ace="http://www.icefaces.org/icefaces/components"
	xmlns:ice="http://www.icesoft.com/icefaces/component"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Result - Analysis</title>

	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<!-- load diagram-js styles and bpmn styles including the cool bpmn font -->
	<h:outputStylesheet library="webjars"
		name="bpmn-js/0.12.0/assets/diagram-js.css" />
	<h:outputStylesheet library="webjars"
		name="bpmn-js/0.12.0/assets/bpmn-font/css/bpmn-embedded.css" />

	<h:outputStylesheet library="css" name="modeler.css" />

	<!-- load jquery -->
	<h:outputScript library="webjars" name="jquery/2.1.3/jquery.js" />

	<!-- load bpmn-js dependencies -->
	<h:outputScript library="webjars" name="lodash/2.4.1-6/lodash.min.js" />
	<h:outputScript library="webjars" name="sax/0.6.0/lib/sax.js" />
	<h:outputScript library="webjars" name="Snap.svg/0.3.0/snap.svg-min.js" />
	<h:outputScript library="webjars" name="jquery-mousewheel/3.1.11/jquery.mousewheel.js" />

	<!-- bpmn-js viewer -->
	
<!-- RES_NOT_FOUND -->
	<h:outputScript library="webjars" name="bpmn-js/0.12.0/bpmn-viewer.js" />
	<h:outputScript library="webjars" name="bpmn-js/0.12.0/bpmn-navigated-viewer.min.js" />

</h:head>
<h:body>

	<h:form>










		<h:commandButton value="Return"
			action="#{pageController.navigatePageCF}" />



		<br />

	
		<!--    <ace:accordion id="accordionPanel" autoHeight="false" event="mouseover" effect="bounceslide">
           
            <c:forEach items="#{DataAnalysis.guidelines}"
			var="data" varStatus="status">-->
		<!--   <ace:accordionPane id="toGL_#{status.index}" title="GuideLane ID: #{data.id} - #{data.name}"  style="background-color: #{data.color}" >-->
	
	<p:panelGrid  border="1"  cellspacing="1" style="width: 100%;">
	<f:facet name="header" >
	 <p:row>
	 <p:column colspan="2">
		<h:outputText value="BEBoP Result " style="font-weight: bold;font-size:20px" />	
		<br/>
		<h:outputText  value="Guidelines respected: " />
			<h:outputText  value="#{DataAnalysis.statistics}" style="font-weight: bold; background-color: #{DataAnalysis.color};" />
		</p:column>
		</p:row>
		</f:facet>
		<p:row>
		
		<p:column rowspan="1" style="width: 37%;">
		<p:accordionPanel value="#{DataAnalysis.guidelines}" var="data"
			style="border: 1px solid #a8a8a8;" multiple="false">
			<p:tab title="Guideline ID: #{data.id} - #{data.name}"
				titleStyle="background: #{data.color};">
				<h:outputText value="Description: " style="font-weight: bold;" />
				<h:outputText value="#{data.description}" />

				<br />
				<h:outputText value="Suggestion: " style="font-weight: bold;" />
				<h:outputText value="#{data.suggestion}" />
				<br />
				<p:accordionPanel value="#{data.elements}" var="element"
					style="border: 1px solid #a8a8a8;" multiple="false">

					<p:tab title="Element Name: #{element.name}"
						titleStyle="background: #{data.color};">
						<h:outputText
							value="Element ID: #{element.value} Process Ref: #{element.refprocessid}" />

					</p:tab>
				</p:accordionPanel>
			</p:tab>
		</p:accordionPanel>
		</p:column>
		<!--   </ace:accordionPane>
                </c:forEach>-->
		<!-- </ace:accordion>-->
		<p:column rowspan="1">
		<div class="content" id="js-drop-zone" style="height:805px;">
		<div id="diagramCanvas"/>
	</div>
	</p:column>
</p:row>
</p:panelGrid>
	</h:form>

<script src="bower-bpmn-js/dist/bpmn-viewer.js"></script>
	
<h:outputScript>	


		var data =' #{DataAnalysis.data}';
		
		if(data!=null){
		<!-- console.log(data);  -->
		openFromUrl(data);
		}
		
		function openFromUrl(data) {
			var BpmnViewer = window.BpmnJS;
			var viewer = new BpmnViewer({container : '#diagramCanvas'});


			var container = $('#js-drop-zone');

			viewer.importXML(data, function(err) {
				if (err) {
					console.log('error rendering', err);
				} else {
					var canvas = viewer.get('canvas');
					// zoom to fit full viewport
					canvas.zoom('fit-viewport');
					container.removeClass('with-error')
							.addClass('with-diagram');
					var guidelineelements = '#{DataAnalysis.elements}';
					if(guidelineelements!=null){
						var gs= guidelineelements.split(",");
							gs.forEach(function(elements) {
							console.log(elements);
								var ele = elements.replace('[','').replace(']','').replace(' ','');
										canvas.addMarker(ele, 'highlight');
										console.log("canvas.addMarker(ele, highlight): "+ele );
						
								});
					}
							 
							 
						
		   						
		   						 var eventBus = viewer.get('eventBus');

		   					    // you may hook into any of the following events
		   					    var events = [
		   					      'element.hover',
		   					      'element.out',
		   					      'element.click',
		   					      'element.dblclick',
		   					      'element.mousedown',
		   					      'element.mouseup'
		   					    ];

		   					    events.forEach(function(event) {
									if(event!=null)
									if(eventBus!=null){
		   					      eventBus.on(event, function(e) {
		   					        // e.element = the model element
		   					        // e.gfx = the graphical element
		   					        if(event=='element.click')
									alert("Element ID: "+ e.element.id);
		   					        console.log(event, 'on', e.element.id);
		   					      });
		   					      }
		   					    });	
							
						
				}
			});
			
			

		};
		
		
		
	</h:outputScript>




	<br />


	<br />





	<h:outputText style="font-weight: bold;font-size:200%;"
		value="XML Version:" />
	<br />
	<br />
	<h:outputText value="#{DataAnalysis.xml}"
		style="white-space: pre-wrap;" styleClass="sxml" />



<br/>

<p>*This work has been partially founded by <a href="http://www.learnpad.eu" target="_blank">EU project LearnPAd</a>  (GA:619583).</p>

<br/>
<br/>
<h:panelGrid columns="2" border="0" layout="block">
<h:panelGroup>
<div style="width: 600px;">
<p align="center">
 <a href="http://www.fmt.isti.cnr.it" target="_blank">Formal Methods &amp; Tools Group</a><br/>
<a href="http://www.isti.cnr.it" target="_blank">Institute of information science and technologies "Alessandro Faedo"</a><br/>  
<a href="http://www.cnr.it" target="_blank"><img  src="images/Logo_CNR-2010-ENG-high.png" style="height: 80px;" /></a>
</p>
</div>
</h:panelGroup>
<h:panelGroup>
<div style="width: 300px;">
<p align="center">
<a href="http://www.cs.unicam.it/" target="_blank">Computer Science Division</a><br/>
<a href="http://www.cs.unicam.it/" target="_blank">University of Camerino</a><br/>
<a href="http://www.unicam.it" target="_blank"><img  src="images/Logo_unicam.png" style="height: 80px; "  /></a><br/>
</p>
</div>
</h:panelGroup>
</h:panelGrid>
</h:body>
</html>

BEBoP-WebUserInterfaces/src/main/webapp/index.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<%
    response.sendRedirect("contentform.jsf");
%>

BEBoP-WebUserInterfaces/src/main/webapp/page1.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:icecore="http://www.icefaces.org/icefaces/core"
	xmlns:ace="http://www.icefaces.org/icefaces/components"
	xmlns:ice="http://www.icesoft.com/icefaces/component">
<h:head>
	<title>Window Scope - Page 1</title>
</h:head>
<h:body>
	<h2>Page 1</h2>
	
	
	<h:form>
		<h:panelGrid columns="4">
		
			<h:commandButton value="Redirect to Page GA" action="#{pageController.navigatePageGetAnalysis}"/>
			<h:commandButton value="Redirect to Page CF" action="#{pageController.navigatePageCF}"/>
			<h:commandButton value="Refresh Page" action="#{pageController.navigatePage1}"/>
		</h:panelGrid>
	</h:form>
	
	<xmp>
	<html>
	</html>
	
	
	</xmp>
	
	
</h:body>
</html>

BEBoP-WebUserInterfaces/src/main/webapp/rex.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:icecore="http://www.icefaces.org/icefaces/core"
	xmlns:ace="http://www.icefaces.org/icefaces/components"
	xmlns:ice="http://www.icesoft.com/icefaces/component"
	xmlns:p="http://primefaces.org/ui">
	
<h:head>
	<title>Window Scope - Page 1</title>
</h:head>
<h:body>
	<h2>Page 1</h2>
	<!-- <f:facet name="last">
		<h:outputStylesheet library="css" name="style.css" />
	</f:facet> -->
	
	<h:form prependId="false">
		<!-- style="background: red;" styleClass="" -->
`		<ace:accordion  id="accordion" collapsible="true" autoHeight="false" >
			<ace:accordionPane  id="maiz" title="Maiz"   >
			<h:panelGrid columns="3" style=".ui-state-default {color: red;}">
			<ice:outputText value="ciao " />
						</h:panelGrid>
			
			</ace:accordionPane>

			<ace:accordionPane id="cafe" title="Café">
			</ace:accordionPane>

			<ace:accordionPane id="papa" title="Papa">
			</ace:accordionPane>
		</ace:accordion>
		
		 <ace:panel id="panel" style="background: green;"
                       header="ICEfaces Header"
                       closable="true"
                       toggleable="true"
                       collapsed="true">
                
                <h:panelGrid>
                    <h:outputText value="ICEfaces 2 is an open-source Rich Internet Application (RIA) development framework based on the JavaServer Faces (JSF) 2 standard. Like its predecessor, ICEfaces 1.8, ICEfaces 2 extends JSF to simplify development and enhance the standard JSF feature set - simultaneously improving developer efficiency and expanding the spectrum of RIA capabilities that can be included in any JSF-based web application."/>
                    <h:outputText value="Adhering closely to the standard JSF 2 extension points allows ICEfaces to work transparently with the stock JSF framework, simplifying integration and fostering 3rd party compatibility with other JSF 2-compliant libraries."/>
                </h:panelGrid>
            </ace:panel>
	
	 <ace:panel id="panel2" style="background: red;"
                       header="ICEfaces Header"
                       closable="false"
                       toggleable="true"
                       collapsed="true">
                
                <h:panelGrid >
                    <h:outputText value="ICEfaces 2 is an open-source Rich Internet Application (RIA) development framework based on the JavaServer Faces (JSF) 2 standard. Like its predecessor, ICEfaces 1.8, ICEfaces 2 extends JSF to simplify development and enhance the standard JSF feature set - simultaneously improving developer efficiency and expanding the spectrum of RIA capabilities that can be included in any JSF-based web application."/>
                    <h:outputText value="Adhering closely to the standard JSF 2 extension points allows ICEfaces to work transparently with the stock JSF framework, simplifying integration and fostering 3rd party compatibility with other JSF 2-compliant libraries."/>
                </h:panelGrid>
            </ace:panel>
            
            
            <h3>DataModel</h3>
    <p:accordionPanel value="CIAO" var="car" style="background-color:  #47d147;">
        <p:tab title="Car - " titleStyle="background:  #47d147;" ariaLabel="ll" >
           
                                 
                <h:outputText value="Brand:" style="font-weight: bold; background:  white;" />
              
 
                <h:outputText value="Year:" style="font-weight: bold" />
               
 
                <h:outputText value="Color:" style="font-weight: bold" />
               
          
        </p:tab>
    </p:accordionPanel> 
            
	
	</h:form>
	
	
</h:body>
</html>

BEBoP-WebUserInterfaces/src/main/webapp/sessionExpiredPage.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:icecore="http://www.icefaces.org/icefaces/core"
	xmlns:ace="http://www.icefaces.org/icefaces/components"
	xmlns:ice="http://www.icesoft.com/icefaces/component">
     
  
     
<h:head>
	<title>Session Expired</title>
</h:head>
<h:body>

	<h:outputText value="Session Expired" style="font-weight: bold;font-size:200%;"/>
<br/>
	<h:form>
	<h:commandButton value="Start New Session" action="#{pageController.navigatePageCF}"/>
	</h:form>
	
	
</h:body>
</html>